### PR TITLE
Update REVIEW2.md

### PR DESCRIPTION
**Pull request by abhidotravi**
Minor changes to have runnable code snippets

### CODE REVIEW

**Comment by yatish27** [comment]
:+1:

**Comment by timm** [comment]
huh... this is strange. i can't see the pathname for this file in this pull request

the reason i ask is that athere are 2 REVIEW2.md files in the repo
- one in the root which is auto-generated
- from src/doc/REVIEW2.md

so can you tell which one have you changed? or tell me how to use github so i can find out?

t

**Comment by abhidotravi** [comment]
I was unaware that the one in the root was auto-generated. If I had looked at the parent commit, I would have known. 

You are not able to see the path because I tried to change the file in the root.

Do you want me to close this request and submit another one for src/doc/REVIEW2.md?

**Comment by timm** [comment]
> Do you want me to close this request and submit another one for src/doc/REVIEW2.md?

that would be cleanest

thanks

t

**Comment by abhidotravi** [comment]
Creating a new pull request for src/doc/REVIEW2.md

**Pull request closed without merging**
